import type { DemoSiteConfig, DemoTheme } from "@/components/demo-site-template";

const goldTheme: DemoTheme = {
  shellBg: "#f6f0e4",
  shellText: "#1f2937",
  shellBorder: "rgba(216,199,163,0.34)",
  topBarBg: "#1b2430",
  topBarText: "#f5dfb1",
  topBarSubtle: "rgba(247,239,224,0.72)",
  sectionLight: "#fffaf1",
  sectionAlt: "#f8f3e8",
  sectionWarm: "linear-gradient(135deg,#d6ba8a 0%,#f2e8d2 42%,#e9dcc0 100%)",
  cardBg: "#ffffff",
  softCardBg: "#fcf8ef",
  softBorder: "rgba(217,201,170,0.58)",
  accentText: "#9a7b48",
  accentBg: "#b68844",
  accentSoftBg: "#f0e0c1",
  darkPanel: "#1b2430",
  darkPanelText: "#ffffff",
  buttonPrimaryBg: "#b68844",
  buttonPrimaryText: "#ffffff",
  phoneButtonBg: "#182230",
  phoneButtonText: "#f9fbff",
  phoneButtonBorder: "rgba(24,34,48,0.2)",
};

const clinicTheme: DemoTheme = {
  shellBg: "#eef7f5",
  shellText: "#17303a",
  shellBorder: "rgba(129,182,171,0.34)",
  topBarBg: "#16313a",
  topBarText: "#c7f2ea",
  topBarSubtle: "rgba(222,247,242,0.72)",
  sectionLight: "#f8fdfc",
  sectionAlt: "#eff8f6",
  sectionWarm: "linear-gradient(135deg,#baded6 0%,#eef9f6 42%,#dcefe9 100%)",
  cardBg: "#ffffff",
  softCardBg: "#f5fbf9",
  softBorder: "rgba(153,201,191,0.58)",
  accentText: "#2f7c70",
  accentBg: "#2f7c70",
  accentSoftBg: "#d8efe9",
  darkPanel: "#16313a",
  darkPanelText: "#ffffff",
  buttonPrimaryBg: "#2f7c70",
  buttonPrimaryText: "#ffffff",
  phoneButtonBg: "#16313a",
  phoneButtonText: "#f9fbff",
  phoneButtonBorder: "rgba(22,49,58,0.2)",
};

const lawTheme: DemoTheme = {
  shellBg: "#f3f1ee",
  shellText: "#1f2730",
  shellBorder: "rgba(170,162,148,0.34)",
  topBarBg: "#202733",
  topBarText: "#f0d8ad",
  topBarSubtle: "rgba(237,229,216,0.72)",
  sectionLight: "#fbfaf8",
  sectionAlt: "#f3f1ee",
  sectionWarm: "linear-gradient(135deg,#d3c8bb 0%,#f1ece6 42%,#e2d8cb 100%)",
  cardBg: "#ffffff",
  softCardBg: "#f8f5f1",
  softBorder: "rgba(201,191,177,0.58)",
  accentText: "#8a6842",
  accentBg: "#8a6842",
  accentSoftBg: "#e8ddd0",
  darkPanel: "#202733",
  darkPanelText: "#ffffff",
  buttonPrimaryBg: "#8a6842",
  buttonPrimaryText: "#ffffff",
  phoneButtonBg: "#202733",
  phoneButtonText: "#f9fbff",
  phoneButtonBorder: "rgba(32,39,51,0.2)",
};

const serviceTheme: DemoTheme = {
  shellBg: "#f4f6f8",
  shellText: "#1e2933",
  shellBorder: "rgba(154,171,189,0.34)",
  topBarBg: "#13202b",
  topBarText: "#f7bf83",
  topBarSubtle: "rgba(230,237,244,0.72)",
  sectionLight: "#fafcfd",
  sectionAlt: "#f1f5f8",
  sectionWarm: "linear-gradient(135deg,#d1dee7 0%,#eef4f8 42%,#dde7ee 100%)",
  cardBg: "#ffffff",
  softCardBg: "#f6fafc",
  softBorder: "rgba(185,199,212,0.58)",
  accentText: "#bc6d1a",
  accentBg: "#bc6d1a",
  accentSoftBg: "#f7e1c7",
  darkPanel: "#13202b",
  darkPanelText: "#ffffff",
  buttonPrimaryBg: "#bc6d1a",
  buttonPrimaryText: "#ffffff",
  phoneButtonBg: "#13202b",
  phoneButtonText: "#f9fbff",
  phoneButtonBorder: "rgba(19,32,43,0.2)",
};

const beautyTheme: DemoTheme = {
  shellBg: "#fbf3f5",
  shellText: "#32202a",
  shellBorder: "rgba(219,173,190,0.34)",
  topBarBg: "#38222f",
  topBarText: "#ffd2df",
  topBarSubtle: "rgba(253,234,241,0.72)",
  sectionLight: "#fff9fb",
  sectionAlt: "#fcf1f5",
  sectionWarm: "linear-gradient(135deg,#efc7d5 0%,#fff2f6 42%,#f8dde6 100%)",
  cardBg: "#ffffff",
  softCardBg: "#fff7fa",
  softBorder: "rgba(230,194,207,0.58)",
  accentText: "#b25579",
  accentBg: "#b25579",
  accentSoftBg: "#f8dce7",
  darkPanel: "#38222f",
  darkPanelText: "#ffffff",
  buttonPrimaryBg: "#b25579",
  buttonPrimaryText: "#ffffff",
  phoneButtonBg: "#38222f",
  phoneButtonText: "#f9fbff",
  phoneButtonBorder: "rgba(56,34,47,0.2)",
};

const restaurantTheme: DemoTheme = {
  shellBg: "#f7f1e7",
  shellText: "#2a201a",
  shellBorder: "rgba(192,157,120,0.34)",
  topBarBg: "#2b1f19",
  topBarText: "#f6d59e",
  topBarSubtle: "rgba(244,232,214,0.72)",
  sectionLight: "#fff9f1",
  sectionAlt: "#f8f0e4",
  sectionWarm: "linear-gradient(135deg,#d9b68b 0%,#f7ead7 42%,#ead6b8 100%)",
  cardBg: "#ffffff",
  softCardBg: "#fdf7ef",
  softBorder: "rgba(222,195,161,0.58)",
  accentText: "#b25d28",
  accentBg: "#b25d28",
  accentSoftBg: "#f4dfca",
  darkPanel: "#2b1f19",
  darkPanelText: "#ffffff",
  buttonPrimaryBg: "#b25d28",
  buttonPrimaryText: "#ffffff",
  phoneButtonBg: "#2b1f19",
  phoneButtonText: "#f9fbff",
  phoneButtonBorder: "rgba(43,31,25,0.2)",
};

export const demoSiteConfigs: Record<string, DemoSiteConfig> = {
  emlak: {
    slug: "emlak",
    categoryLabel: "Bölge Uzmanlığı",
    brandName: "Yıldız Emlak Ofisi",
    heroTitle: "Körfez ve çevresinde doğru portföy, net sunum, hızlı temas.",
    heroDescription: "Gayrimenkulü yalnızca listelemeyen, doğru sunan emlak sitesi örneği.",
    topNote: "Bu sayfa örnek emlak sitesi hissi vermesi için hazırlandı.",
    categoryChips: ["Satılık Daire", "Villa", "Ticari Alan", "Kiralık Ofis"],
    metrics: [
      { label: "Aktif Portföy", value: "126" },
      { label: "Ana Odak", value: "3 Bölge" },
      { label: "Geri Dönüş", value: "15 dk" },
    ],
    quickSearchTitle: "Size uygun portföyü bulun",
    quickSearchRows: ["İşlem Türü: Satılık", "Bölge: Körfez / Başiskele / İzmit", "Gayrimenkul: Daire / Villa / Ofis"],
    quickSearchNote: "Doğrudan danışmana bağlanın",
    listingsTitle: "Gerçek bir emlak sitesi gibi gezilebilecek örnek ilan düzeni",
    listingsSubtitle:
      "Kullanıcı bölgeyi, fiyat seviyesini ve danışmana ulaşma yolunu birkaç saniyede görür. Demo mantığı tam olarak bu: açıklama sayfası değil, gerçek site hissi.",
    featuredListings: [
      { title: "Körfez'de Deniz Manzaralı 3+1 Daire", type: "Satılık Daire", location: "Yarımca, Körfez / Kocaeli", price: "4.850.000 TL", area: "145 m²", beds: "3+1", baths: "2 Banyo", tag: "Öne Çıkan" },
      { title: "Başiskele'de Bahçeli Müstakil Villa", type: "Satılık Villa", location: "Başiskele / Kocaeli", price: "11.400.000 TL", area: "280 m²", beds: "5+1", baths: "3 Banyo", tag: "Yeni İlan" },
      { title: "İzmit Merkez'de Kurumsal Ofis Katı", type: "Kiralık Ofis", location: "İzmit / Kocaeli", price: "68.000 TL / ay", area: "210 m²", beds: "Açık Plan", baths: "2 WC", tag: "Ticari" },
    ],
    areasTitle: "Kullanıcı hangi bölgelerde güçlü olduğunuzu hemen görmeli",
    areasLead: "Bölge gücü emlak tarafında ilk güven unsurlarından biridir.",
    areas: [
      { name: "Körfez", detail: "Aile yaşamına uygun siteler, sahil hattı ve yatırım potansiyeli yüksek daire portföyleri." },
      { name: "Başiskele", detail: "Villa, müstakil yaşam ve yeni nesil konut projeleri için güçlü bölge sunumu." },
      { name: "İzmit", detail: "Merkezi yaşam, ticari gayrimenkul ve kiralık ofis tarafında aktif portföy akışı." },
    ],
    reasonsTitle: "Emlak sitesi önce güven, sonra portföy, sonra temas sunmalı",
    reasonsLead: "Bu sırayı bozmadığınızda ziyaretçi ne baktığını, ne yapacağını ve kime ulaşacağını hemen anlar.",
    reasons: ["Bölgeyi bilen danışman ekibi", "Portföyleri filtrelenebilir düzende sunan yapı", "Telefon ve WhatsApp temasını hızlandıran sayfa akışı", "Müşterinin karar verirken görmek istediği bilgiyi öne çıkaran düzen"],
    advisorName: "Mert Yıldız",
    advisorRole: "Körfez ve Başiskele Konut Danışmanı",
    advisorNote: "Bu bölüm gerçek sitede danışman biyografisi, referans cümlesi ve hızlı iletişim butonlarıyla güveni kuvvetlendirir.",
    processTitle: "İyi demo site yalnızca güzel görünmez, süreci de anlatır",
    processLead: "Ziyaretçi adım adım nasıl ilerleyeceğini gördüğünde arama kararı hızlanır.",
    processSteps: ["İhtiyaç belirlenir ve doğru portföy seçilir", "Yer gösterme ve ön değerlendirme yapılır", "Pazarlık ve evrak süreci kontrollü ilerler", "Teslim sonrası destek ile süreç tamamlanır"],
    contactTitle: "Bu demoda ziyaretçi tek ekranda arama, mesaj ve talep bırakma yolunu görür",
    contactLead: "İletişim alanı kolay, net ve görünür olmalıdır; özellikle mobil kullanıcı için.",
    contactPlaceholders: ["Ad Soyad", "Telefon Numarası", "Aradığınız portföy tipi"],
    faqsTitle: "Bu örneğin amacı tam olarak anlaşılmalı",
    faqsLead: "Emlak sektöründe demo sayfanın ne gösterdiği açık olmalı.",
    faqs: [
      { question: "Portföyler nasıl öne çıkarılmalı?", answer: "Fiyat, konum, metrekare ve kısa özet ilk bakışta görünmeli. Kullanıcı detay için ikinci adıma geçmeli, ilk ekranda boğulmamalı." },
      { question: "Emlak sitesinde en kritik bölüm nedir?", answer: "İlk ekran ve öne çıkan ilanlar alanı. Ziyaretçi güvene ve uygun portföye çok hızlı bakar; bu akış gecikirse dönüş ihtimali düşer." },
      { question: "Bu demo birebir kullanıma uygun mu?", answer: "Bu örnek, gerçek site mantığını göstermek için hazırlandı. İçerik, bölge ve portföy yapısı işletmeye özel olarak yeniden düzenlenir." },
    ],
    theme: goldTheme,
  },
  klinik: {
    slug: "klinik",
    categoryLabel: "Hasta Güveni",
    brandName: "Nova Klinik",
    heroTitle: "Uzman yaklaşımı net gösteren, randevuyu kolaylaştıran klinik sitesi.",
    heroDescription: "Hasta güveni, doktor görünürlüğü ve randevu akışı odaklı klinik demo.",
    topNote: "Bu sayfa örnek klinik sitesi hissi vermesi için hazırlandı.",
    categoryChips: ["Cilt Sağlığı", "Lazer", "Dermatoloji", "Online Randevu"],
    metrics: [{ label: "Uzman Doktor", value: "4" }, { label: "Aktif Branş", value: "7" }, { label: "Randevu Süresi", value: "30 sn" }],
    quickSearchTitle: "İşleminizi hızlı seçin",
    quickSearchRows: ["Branş: Dermatoloji", "İşlem: Muayene / Cilt Bakımı / Lazer", "Randevu Türü: Online / Telefon"],
    quickSearchNote: "Randevuyu geciktirmeden başlatın",
    listingsTitle: "Gerçek klinik sitesi gibi gezi hissi veren hizmet düzeni",
    listingsSubtitle: "Klinik tarafında kullanıcı önce işlem alanını, sonra doktoru, sonra randevu akışını görmek ister.",
    featuredListings: [
      { title: "Uzman Dermatoloji Muayenesi", type: "Muayene", location: "Yahyakaptan, İzmit", price: "Aynı Gün Randevu", area: "30 dk", beds: "Uzman Doktor", baths: "Tetkik", tag: "Yoğun Talep" },
      { title: "Medikal Cilt Bakımı Programı", type: "Bakım Paketi", location: "Kocaeli Klinik Merkezi", price: "Kişiye Özel Plan", area: "45 dk", beds: "3 Aşama", baths: "Kontrol", tag: "Popüler" },
      { title: "Lazer Epilasyon Ön Görüşmesi", type: "Ön Değerlendirme", location: "Başiskele Şubesi", price: "Ücretsiz Görüşme", area: "20 dk", beds: "Cihaz Seçimi", baths: "Planlama", tag: "Yeni" },
    ],
    areasTitle: "Klinik sitesinde önce güven veren branş ve ekip görünmeli",
    areasLead: "Her branş ayrı güven sinyali üretir; kullanıcı bunu başta görmelidir.",
    areas: [
      { name: "Dermatoloji", detail: "Muayene, leke tedavisi ve kişiye özel cilt takip hizmetlerini net biçimde sunar." },
      { name: "Estetik Uygulamalar", detail: "Uygulama başlıkları abartısız ama güven veren anlatımla düzenlenir." },
      { name: "Lazer ve Bakım", detail: "Süreç, cihaz ve seans mantığı sade açıklamalarla aktarılır." },
    ],
    reasonsTitle: "Klinik sitesi, hastaya karmaşa değil güven vermeli",
    reasonsLead: "Yanlış kurgu klinik sitesini broşür gibi gösterir; doğru kurgu ise randevuya dönüştürür.",
    reasons: ["Uzman ekibi öne çıkaran yapı", "Hizmet başlıklarını sadeleştiren düzen", "Randevu kararını geciktirmeyen CTA akışı", "Sık sorulanları erken cevaplayan içerik sırası"],
    advisorName: "Dr. Selin Acar",
    advisorRole: "Dermatoloji Uzmanı",
    advisorNote: "Doktor tanıtımı bu alanda kısa özgeçmiş, uzmanlık ve güven notları ile desteklenir.",
    processTitle: "Hasta süreci görünür olursa iletişim daha hızlı başlar",
    processLead: "Randevu, ön değerlendirme ve işlem planı net görünmelidir.",
    processSteps: ["Uygun branş veya işlem seçilir", "Ön bilgi ve randevu alınır", "Muayene veya değerlendirme yapılır", "Kişiye özel plan ile süreç sürdürülür"],
    contactTitle: "Klinik demosunda ziyaretçi randevu yolunu tek bakışta anlamalı",
    contactLead: "Telefon, form ve hızlı randevu çağrısı birlikte görünmelidir.",
    contactPlaceholders: ["Ad Soyad", "Telefon Numarası", "İlgilendiğiniz işlem"],
    faqsTitle: "Klinik demosunun amacı nedir?",
    faqsLead: "Bu örnek klinik web sitesi kurgusunun nasıl çalıştığını gösterir.",
    faqs: [
      { question: "Klinik sitesi neden sade olmalı?", answer: "Hasta önce güven arar. Fazla hareket ve yoğun bilgi güven yerine yorgunluk üretir." },
      { question: "En kritik CTA hangisi?", answer: "Randevu al ve telefonla ulaş alanları. Kullanıcı beklemeden karar vermelidir." },
      { question: "Bu demo hangi klinikler için uygundur?", answer: "Dermatoloji, güzellik-klinik hibrit yapı, estetik ve muayene odaklı merkezler için iyi temel sunar." },
    ],
    theme: clinicTheme,
  },
  avukat: {
    slug: "avukat",
    categoryLabel: "Kurumsal Güven",
    brandName: "Yalçın Hukuk Bürosu",
    heroTitle: "Uzmanlık alanlarını sade anlatan, güven veren hukuk bürosu sitesi.",
    heroDescription: "Danışmanlık talebini kolaylaştıran, ağır ama modern duran avukat demo sitesi.",
    topNote: "Bu sayfa örnek avukat sitesi hissi vermesi için hazırlandı.",
    categoryChips: ["Ceza Hukuku", "Aile Hukuku", "İcra", "Kurumsal Danışmanlık"],
    metrics: [{ label: "Uzmanlık Alanı", value: "6" }, { label: "Ön Görüşme", value: "1 Gün" }, { label: "Kurumsal Müvekkil", value: "42+" }],
    quickSearchTitle: "Doğru hukuki alanı seçin",
    quickSearchRows: ["Hukuk Alanı: Aile / Ceza / İcra", "Danışmanlık Türü: Bireysel / Kurumsal", "Görüşme Şekli: Ofis / Online"],
    quickSearchNote: "Danışmanlık talebini hızlı başlatın",
    listingsTitle: "Gerçek hukuk bürosu sitesi gibi çalışan hizmet sunumu",
    listingsSubtitle: "Bu yapı kullanıcıya önce hangi alanda destek verildiğini, sonra nasıl ilerleyeceğini gösterir.",
    featuredListings: [
      { title: "Boşanma ve Velayet Danışmanlığı", type: "Aile Hukuku", location: "Kocaeli Merkez", price: "Ön Görüşme Planlanır", area: "Dosya Analizi", beds: "Duruşma", baths: "Takip", tag: "Yoğun Talep" },
      { title: "İcra Takibi ve Alacak Süreci", type: "İcra Hukuku", location: "Kurumsal ve Bireysel", price: "Süreç Bazlı", area: "Takip", beds: "Tahsilat", baths: "Rapor", tag: "Kurumsal" },
      { title: "Şirket Sözleşme Danışmanlığı", type: "Kurumsal Hukuk", location: "Kocaeli / İstanbul", price: "Aylık Danışmanlık", area: "Risk Analizi", beds: "Sözleşme", baths: "Revizyon", tag: "Süreç" },
    ],
    areasTitle: "Avukat sitesinde güveni uzmanlık alanları taşır",
    areasLead: "Ziyaretçi önce ne konuda destek aldığını net görmelidir.",
    areas: [
      { name: "Aile Hukuku", detail: "Boşanma, velayet ve mal paylaşımı süreçlerini açık ve ölçülü biçimde sunar." },
      { name: "İcra ve Alacak", detail: "Takip, tahsilat ve resmi süreçleri güven veren dil ile anlatır." },
      { name: "Kurumsal Danışmanlık", detail: "Şirketlerin düzenli sözleşme ve süreç desteğini ayrı bir profesyonel blokta sunar." },
    ],
    reasonsTitle: "Hukuk bürosu sitesi iddialı değil, ciddi görünmelidir",
    reasonsLead: "Abartılı tasarım yerine kontrol, güven ve net başlıklar önemlidir.",
    reasons: ["Uzmanlık alanlarını açık ayıran yapı", "Danışmanlık talebini kolaylaştıran akış", "Kurumsal güven veren tipografi ve renk yapısı", "Müvekkilin ilk sorularını önceden cevaplayan içerik sırası"],
    advisorName: "Av. Eren Yalçın",
    advisorRole: "Kurucu Avukat",
    advisorNote: "Bu blokta avukat özgeçmişi, baro kaydı ve hizmet disiplinine dair kısa bilgiler yer alır.",
    processTitle: "Danışan ilk görüşmede nasıl ilerleyeceğini anlamalı",
    processLead: "Süreç şeffaf oldukça başvuru eşiği düşer.",
    processSteps: ["Hukuki alan belirlenir", "Ön görüşme ve dosya değerlendirmesi yapılır", "Yol haritası ve dava / takip süreci netleştirilir", "Düzenli bilgilendirme ile süreç yürütülür"],
    contactTitle: "Avukat demosunda ziyaretçi başvuru kanalını kolayca görmeli",
    contactLead: "Ön görüşme talebi, telefon ve iletişim formu aynı blokta olmalıdır.",
    contactPlaceholders: ["Ad Soyad", "Telefon Numarası", "İlgili hukuk alanı"],
    faqsTitle: "Bu hukuk demosu neyi gösteriyor?",
    faqsLead: "Örnek bir avukat sitesinin güvenli ve profesyonel nasıl kurgulanacağını gösterir.",
    faqs: [
      { question: "Hukuk sitesinde en kritik başlık nedir?", answer: "Uzmanlık alanları. Kullanıcı kendine uygun alanı ilk bakışta seçebilmelidir." },
      { question: "İletişim alanı ne kadar görünür olmalı?", answer: "Ciddi ama kolay erişilebilir olmalı; ziyaretçi aramak için site içinde kaybolmamalıdır." },
      { question: "Bu demo kimler için uygundur?", answer: "Bireysel ve kurumsal danışmanlık sunan hukuk büroları için güçlü başlangıç yapısıdır." },
    ],
    theme: lawTheme,
  },
  "oto-servis": {
    slug: "oto-servis",
    categoryLabel: "Servis Güveni",
    brandName: "Atlas Oto Servis",
    heroTitle: "Araç sahibinin hızlı karar verebildiği, net servis akışına sahip oto servis sitesi.",
    heroDescription: "Bakım, arıza ve hızlı randevu akışını öne çıkaran oto servis demo sitesi.",
    topNote: "Bu sayfa örnek oto servis sitesi hissi vermesi için hazırlandı.",
    categoryChips: ["Periyodik Bakım", "Motor", "Fren", "Bilgisayarlı Arıza Tespiti"],
    metrics: [{ label: "Servis Noktası", value: "2" }, { label: "Araç Kabul", value: "Aynı Gün" }, { label: "Marka Desteği", value: "12+" }],
    quickSearchTitle: "Servis ihtiyacınızı seçin",
    quickSearchRows: ["Hizmet: Bakım / Arıza / Fren", "Araç Tipi: Binek / Hafif Ticari", "Marka: Çoklu Marka Desteği"],
    quickSearchNote: "Araç sahibini hızlıca ustaya bağlayın",
    listingsTitle: "Gerçek servis sitesi gibi gezilecek hizmet ve kampanya kartları",
    listingsSubtitle: "Servis sitelerinde kullanıcı önce problemiyle ilgili hizmeti, sonra güven unsurunu, sonra randevu yolunu arar.",
    featuredListings: [
      { title: "Periyodik Bakım Paketi", type: "Bakım Hizmeti", location: "İzmit Sanayi", price: "Aynı Gün Teslim", area: "90 dk", beds: "Yağ + Filtre", baths: "Kontrol", tag: "Yoğun Talep" },
      { title: "Bilgisayarlı Arıza Tespiti", type: "Hızlı Kontrol", location: "Körfez Şubesi", price: "Hızlı Test", area: "30 dk", beds: "OBD Tarama", baths: "Rapor", tag: "Hızlı" },
      { title: "Fren ve Balata Servisi", type: "Güvenlik Kontrolü", location: "Başiskele Servis", price: "Fiyat Teklifi", area: "45 dk", beds: "Balata", baths: "Disk", tag: "Önerilen" },
    ],
    areasTitle: "Servis sitesinde hizmet alanları araç sahibine hızlı görünmeli",
    areasLead: "Sorununu tanıyan kullanıcı çözüm başlığına saniyeler içinde ulaşmalıdır.",
    areas: [
      { name: "Periyodik Bakım", detail: "Standart bakım işlemlerini anlaşılır paket başlıklarıyla gösterir." },
      { name: "Arıza Tespiti", detail: "Bilgisayarlı test ve usta kontrolü tek blokta güven veren anlatımla sunulur." },
      { name: "Fren ve Mekanik", detail: "Güvenlikle ilgili işlemler ayrı vurgulanır; karar verme süresi kısalır." },
    ],
    reasonsTitle: "Oto servis sitesinde kullanıcı beklemek istemez",
    reasonsLead: "Hızlı temas, net hizmet listesi ve marka uyumu en kritik üçlüdür.",
    reasons: ["Servis hizmetlerini sade başlıklara bölen yapı", "Telefon ve konum bilgisini görünür tutan düzen", "Marka bağımsız güven hissi veren içerik akışı", "Araç sahibinin süreçten çekinmesini azaltan açıklamalar"],
    advisorName: "Usta Mehmet Kaya",
    advisorRole: "Servis Sorumlusu",
    advisorNote: "Bu blokta uzman usta profili, deneyim ve servis yaklaşımı güven unsuru olarak kullanılır.",
    processTitle: "Servis süreci görünür olunca arama kararı hızlanır",
    processLead: "Araç sahibi sorununun nasıl ele alınacağını önceden görmek ister.",
    processSteps: ["Araç problemi veya bakım ihtiyacı seçilir", "Telefon ya da form ile servis kaydı oluşturulur", "Kontrol ve teklif süreci başlatılır", "Onay sonrası işlem ve teslim tamamlanır"],
    contactTitle: "Oto servis demosunda kullanıcı tek ekranda arama ve kayıt yolunu görmeli",
    contactLead: "Özellikle mobilde hızlı arama butonu çok görünür olmalıdır.",
    contactPlaceholders: ["Ad Soyad", "Telefon Numarası", "Araç marka / model"],
    faqsTitle: "Bu servis demosu neyi amaçlıyor?",
    faqsLead: "Gerçek servis akışının web sitesinde nasıl sunulacağını gösteriyor.",
    faqs: [
      { question: "Servis sitesinde ne öne çıkarılmalı?", answer: "Hizmet listesi, konum, hızlı arama ve güven veren ekip bilgisi." },
      { question: "Kampanya alanı gerekli mi?", answer: "Evet, ama sınırlı ve düzenli. Kararı desteklemeli, karmaşa üretmemeli." },
      { question: "Bu demo hangi işletmelere uyar?", answer: "Bağımsız oto servisler, çok marka bakım merkezleri ve lokal ustalık odaklı işletmeler için uygundur." },
    ],
    theme: serviceTheme,
  },
  "guzellik-merkezi": {
    slug: "guzellik-merkezi",
    categoryLabel: "Randevu Akışı",
    brandName: "Luna Beauty Studio",
    heroTitle: "İşlem alanlarını zarif gösteren, randevu kararını hızlandıran güzellik merkezi sitesi.",
    heroDescription: "Bakım, uzman ekip ve randevu akışını dengeli sunan güzellik merkezi demo sitesi.",
    topNote: "Bu sayfa örnek güzellik merkezi sitesi hissi vermesi için hazırlandı.",
    categoryChips: ["Cilt Bakımı", "Lazer", "Bölgesel İncelme", "Randevu"],
    metrics: [{ label: "Uzman Ekip", value: "6" }, { label: "İşlem Alanı", value: "9" }, { label: "Hızlı Randevu", value: "1 dk" }],
    quickSearchTitle: "İşlem alanınızı seçin",
    quickSearchRows: ["İşlem: Cilt / Lazer / İncelme", "Görüşme: Ön Bilgi / Randevu", "Şube: Merkez / Başiskele"],
    quickSearchNote: "Randevu kararını kolaylaştırın",
    listingsTitle: "Gerçek güzellik merkezi sitesi gibi çalışan işlem kartları",
    listingsSubtitle: "Bu sektörde kullanıcı işlem başlığını, ortam hissini ve uzmanlığı birlikte görmek ister.",
    featuredListings: [
      { title: "Hydrafacial Cilt Bakımı", type: "Cilt Uygulaması", location: "İzmit Merkez", price: "Kişiye Özel Seans", area: "50 dk", beds: "3 Aşama", baths: "Kontrol", tag: "Popüler" },
      { title: "Lazer Epilasyon Paketi", type: "Lazer", location: "Kadınlara Özel Alan", price: "Paket Görüşmesi", area: "30 dk", beds: "Bölgesel", baths: "Planlama", tag: "Yoğun Talep" },
      { title: "Bölgesel İncelme Programı", type: "Vücut Uygulaması", location: "Başiskele Şubesi", price: "Ücretsiz Ön Görüşme", area: "40 dk", beds: "Analiz", baths: "Takip", tag: "Yeni" },
    ],
    areasTitle: "Güzellik merkezinde işlem başlıkları sade ama güçlü görünmeli",
    areasLead: "Karar estetik hisle başlar ama güvenle tamamlanır.",
    areas: [
      { name: "Cilt Bakımı", detail: "İşlem detayları kısa açıklamalarla düzenlenir, kullanıcı ne alacağını bilir." },
      { name: "Lazer Uygulamaları", detail: "Cihaz, süreç ve seans mantığı açık ama yormayan dil ile sunulur." },
      { name: "Vücut Programları", detail: "Kişiye özel plan yaklaşımı ayrı blokta güven unsuru olarak öne çıkar." },
    ],
    reasonsTitle: "Güzellik sitesi yalnızca güzel değil, düzenli de görünmeli",
    reasonsLead: "Aşırı pembe ve yoğun anlatım yerine kontrollü premium hissi daha güçlü çalışır.",
    reasons: ["İşlem alanlarını kategorik sunan yapı", "Randevu çağrısını görünür tutan akış", "Uzman ekibi güven unsuru yapan bloklar", "Kullanıcıyı işlem seçimine yönlendiren sade düzen"],
    advisorName: "Uzman Derya Yılmaz",
    advisorRole: "Kurucu ve Cilt Uygulama Uzmanı",
    advisorNote: "Bu alanda uzman ekibin yaklaşımı, merkez hikayesi ve müşteri memnuniyeti notları öne çıkar.",
    processTitle: "Randevu akışı sade görünürse dönüşüm yükselir",
    processLead: "Kullanıcı önce işlem seçer, sonra hızlıca randevu alır.",
    processSteps: ["İşlem alanı seçilir", "Ön bilgi veya ücretsiz görüşme planlanır", "Uygun seans programı oluşturulur", "Takip ve memnuniyet süreci sürdürülür"],
    contactTitle: "Güzellik demosunda ziyaretçi hızlı randevu yolunu tek bakışta anlamalı",
    contactLead: "Form ve telefon butonları estetik görünürken güçlü okunurluk korumalıdır.",
    contactPlaceholders: ["Ad Soyad", "Telefon Numarası", "İlgilendiğiniz işlem"],
    faqsTitle: "Bu güzellik demosu hangi amaçla hazırlandı?",
    faqsLead: "İşlem odaklı bir merkezin site yapısını gerçek hisle göstermesi için.",
    faqs: [
      { question: "Bu sektörde en kritik alan hangisi?", answer: "İşlem kartları ve randevu çağrısı. Kullanıcı aradığını hızlı seçebilmelidir." },
      { question: "Görsel ağırlık fazla olmalı mı?", answer: "Hayır. Premium his olmalı ama içerik ve CTA geri planda kalmamalıdır." },
      { question: "Bu demo hangi merkezlere uyar?", answer: "Cilt bakımı, lazer, güzellik ve bakım odaklı butik ya da orta ölçekli merkezlere uygundur." },
    ],
    theme: beautyTheme,
  },
  restoran: {
    slug: "restoran",
    categoryLabel: "Lezzet Akışı",
    brandName: "Miras Sofra",
    heroTitle: "Menüyü, mekanı ve rezervasyon kararını birlikte taşıyan restoran sitesi.",
    heroDescription: "Lezzet, mekan hissi ve rezervasyonu tek akışta sunan restoran demo sitesi.",
    topNote: "Bu sayfa örnek restoran sitesi hissi vermesi için hazırlandı.",
    categoryChips: ["Ana Yemekler", "Izgara", "Tatlılar", "Rezervasyon"],
    metrics: [{ label: "İmza Menü", value: "18" }, { label: "Masa Kapasitesi", value: "120" }, { label: "Rezervasyon", value: "45 sn" }],
    quickSearchTitle: "Masa veya menü planınızı seçin",
    quickSearchRows: ["Deneyim: Akşam Yemeği / Grup / Aile", "Alan: Salon / Teras", "Rezervasyon: Bugün / Tarih Seç"],
    quickSearchNote: "Kararı hızla rezervasyona çevirin",
    listingsTitle: "Gerçek restoran sitesi gibi gezilecek menü ve deneyim kartları",
    listingsSubtitle: "Restoran kullanıcıları önce yemekleri, sonra atmosferi, sonra rezervasyon kolaylığını görmek ister.",
    featuredListings: [
      { title: "Odun Ateşinde Karışık Izgara", type: "İmza Lezzet", location: "Akşam Servisi", price: "Şef Önerisi", area: "2 Kişilik", beds: "Izgara", baths: "Sunum", tag: "En Çok Tercih Edilen" },
      { title: "Teras Akşam Menüsü", type: "Deneyim Paketi", location: "Teras Alanı", price: "Rezervasyonlu", area: "Canlı Müzik", beds: "Fix Menü", baths: "Tatlı", tag: "Akşam" },
      { title: "Aile Kahvaltı Sofrası", type: "Hafta Sonu", location: "Bahçe Katı", price: "Kişi Başı Menü", area: "Serpme", beds: "Sıcaklar", baths: "İçecek", tag: "Hafta Sonu" },
    ],
    areasTitle: "Restoran sitesinde menü ve atmosfer birlikte çalışmalı",
    areasLead: "Karar yalnızca yemekle değil, mekan hissi ve rezervasyon kolaylığıyla tamamlanır.",
    areas: [
      { name: "Izgara ve Ana Yemekler", detail: "İmza tabaklar net fiyat veya kategori mantığıyla görünür." },
      { name: "Mekan Deneyimi", detail: "Salon, teras ve özel alanlar ayrı anlatılarak mekan algısı güçlendirilir." },
      { name: "Rezervasyon Akışı", detail: "Telefon ve masa ayırtma çağrısı tüm karar anlarında görünür tutulur." },
    ],
    reasonsTitle: "Restoran sitesi iştah açmalı ama rezervasyonu unutturmamalı",
    reasonsLead: "Lezzet hissi ile aksiyon çağrısı birlikte ilerlemelidir.",
    reasons: ["Menü kategorilerini hızlı okutabilen yapı", "Mekan hissini fotoğraf düzeni olmadan bile taşıyan akış", "Telefon ve rezervasyon çağrısını görünür tutan tasarım", "Özel deneyim ve etkinlikleri ayrı sunan alanlar"],
    advisorName: "Şef Murat Demir",
    advisorRole: "Kurucu Şef",
    advisorNote: "Bu blokta şef hikayesi, mutfak yaklaşımı ve mekan vizyonu premium hissi kuvvetlendirir.",
    processTitle: "Restoran sitesinde kullanıcı aç kalmamalı, beklememeli",
    processLead: "Menü görür, mekan hissini alır ve rezervasyonu aynı akışta tamamlar.",
    processSteps: ["Kullanıcı deneyim tipini seçer", "Menü ve mekan alanlarını inceler", "Telefon veya form ile rezervasyon başlatır", "Onay ve masa planı tamamlanır"],
    contactTitle: "Restoran demosunda arama ve rezervasyon yolu çok net görünmeli",
    contactLead: "Özellikle akşam servis kararlarında tek dokunuşla iletişim hissi önemlidir.",
    contactPlaceholders: ["Ad Soyad", "Telefon Numarası", "Rezervasyon tarihi / kişi sayısı"],
    faqsTitle: "Bu restoran demosu neyi gösteriyor?",
    faqsLead: "Menü ve rezervasyon odaklı bir restoran sitesinin nasıl kurgulanacağını gösteriyor.",
    faqs: [
      { question: "Restoran sitesinde en önemli alan nedir?", answer: "İmza menüler ve rezervasyon çağrısı. Kullanıcı bunları ilk bakışta görmelidir." },
      { question: "Tüm menü tek sayfada mı olmalı?", answer: "Hayır. Ana kategoriler ana sayfada görünmeli, detay menü daha derine açılmalıdır." },
      { question: "Bu demo hangi işletmelere uyar?", answer: "Aile restoranları, butik mekanlar, ızgara ve akşam yemeği odaklı işletmeler için güçlü temel sunar." },
    ],
    theme: restaurantTheme,
  },
};
